# Generated by Django 5.0.7 on 2024-09-03 18:04

import django.core.validators
import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "preferred_job_types",
                    models.CharField(
                        choices=[
                            ("Full-time", "Full-time"),
                            ("Part-time", "Part-time"),
                            ("Freelance", "Freelance"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=1
                    ),
                ),
                (
                    "contact_number",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Contact number should be 9 digits.",
                                regex="^\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_images/"
                    ),
                ),
                (
                    "work_days",
                    multiselectfield.db.fields.MultiSelectField(
                        blank=True,
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        help_text="Select multiple days using Ctrl or Cmd key",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Mechanic",
            },
        ),
        migrations.CreateModel(
            name="MechanicPricePerService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("Engine Repair", "Engine Repair"),
                            ("Oil Change", "Oil Change"),
                            ("Tire Replacement", "Tire Replacement"),
                            ("Brake Service", "Brake Service"),
                            ("General Maintenance", "General Maintenance"),
                            ("Transmission Repair", "Transmission Repair"),
                            ("Battery Replacement", "Battery Replacement"),
                            ("AC Repair", "AC Repair"),
                            ("Wheel Alignment", "Wheel Alignment"),
                            ("Suspension Repair", "Suspension Repair"),
                            ("Electrical System Repair", "Electrical System Repair"),
                            ("Exhaust System Repair", "Exhaust System Repair"),
                            ("Radiator Repair", "Radiator Repair"),
                            ("Fuel System Repair", "Fuel System Repair"),
                            ("Clutch Repair", "Clutch Repair"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(100)],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("Euro", "Euro"),
                            ("Dollar", "US Dollar"),
                            ("Pound", "British Pound"),
                        ],
                        default="Euro",
                        max_length=6,
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Mechanic.mechanic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mechanic Price Per Service",
                "unique_together": {("mechanic", "service_name", "currency")},
            },
        ),
    ]
