# Generated by Django 5.0.7 on 2024-08-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanic",
            name="specializations",
        ),
        migrations.AddConstraint(
            model_name="mechanicpriceperservice",
            constraint=models.UniqueConstraint(
                fields=("mechanic", "service_name"), name="unique_user_service"
            ),
        ),
    ]
