# Generated by Django 5.0.7 on 2024-08-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanic",
            name="specializations",
        ),
        migrations.AddField(
            model_name="mechanic",
            name="specialization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mechanics",
                to="Mechanic.specialization",
            ),
        ),
    ]
