# Generated by Django 5.0.7 on 2024-08-30 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0002_remove_mechanic_specializations_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mechanic",
            old_name="specialization",
            new_name="specializations",
        ),
    ]
