# Generated by Django 5.0.7 on 2024-08-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Mechanic",
            "0002_remove_mechanic_profile_pic_remove_mechanic_username_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="mechanic",
            name="specializations",
        ),
        migrations.AddField(
            model_name="mechanic",
            name="specializations",
            field=models.ManyToManyField(
                related_name="mechanics", to="Mechanic.specialization"
            ),
        ),
    ]
