# Generated by Django 5.0.7 on 2024-08-30 20:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0003_rename_specialization_mechanic_specializations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mechanic",
            constraint=models.UniqueConstraint(
                fields=("user", "specializations"), name="unique_user_specialization"
            ),
        ),
    ]
