# Generated by Django 5.0.7 on 2024-08-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0003_specialization_remove_mechanic_specializations_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mechanic",
            options={"verbose_name_plural": "Mechanic"},
        ),
        migrations.RemoveField(
            model_name="mechanic",
            name="date_of_join",
        ),
        migrations.RemoveField(
            model_name="mechanic",
            name="email",
        ),
        migrations.RemoveField(
            model_name="mechanic",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="mechanic",
            name="last_name",
        ),
    ]
