# Generated by Django 5.0.7 on 2024-08-30 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Mechanic", "0004_mechanic_unique_user_specialization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mechanic",
            name="specializations",
        ),
    ]
