from .customer import customer_list_create, customer_detail
from .customer_service_request import service_request_detail,list_service_requests
from .customer_feedback import feedback_detail,feedback_list_or_create
