# Generated by Django 5.0.7 on 2024-07-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name_plural": "Customer Profile"},
        ),
    ]
