# Generated by Django 5.0.7 on 2024-08-20 19:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
        (
            "Mechanic",
            "0002_remove_mechanic_profile_pic_remove_mechanic_username_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Two_wheeler_with_gear", "Two_wheeler_with_gear"),
                            ("Two_wheeler_without_gear", "Two_wheeler_without_gear"),
                            ("Four_wheeler", "Four Wheeler"),
                            ("Three_wheeler", "Three_wheeler"),
                        ],
                        max_length=50,
                    ),
                ),
                ("vehicle_no", models.CharField(max_length=20, unique=True)),
                ("vehicle_name", models.CharField(max_length=50)),
                ("vehicle_model", models.CharField(max_length=50)),
                ("vehicle_brand", models.CharField(max_length=50)),
                ("problem_description", models.TextField()),
                (
                    "date_of_request",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("service_needed", models.SmallIntegerField(default=1)),
                (
                    "service_name",
                    models.CharField(
                        choices=[
                            ("Engine Repair", "Engine Repair"),
                            ("Oil Change", "Oil Change"),
                            ("Tire Replacement", "Tire Replacement"),
                            ("Brake Service", "Brake Service"),
                            ("General Maintenance", "General Maintenance"),
                            ("Transmission Repair", "Transmission Repair"),
                            ("Battery Replacement", "Battery Replacement"),
                            ("AC Repair", "AC Repair"),
                            ("Wheel Alignment", "Wheel Alignment"),
                            ("Suspension Repair", "Suspension Repair"),
                            ("Electrical System Repair", "Electrical System Repair"),
                            ("Exhaust System Repair", "Exhaust System Repair"),
                            ("Radiator Repair", "Radiator Repair"),
                            ("Fuel System Repair", "Fuel System Repair"),
                            ("Clutch Repair", "Clutch Repair"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.customer",
                    ),
                ),
                (
                    "mechanic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="Mechanic.mechanic",
                    ),
                ),
            ],
        ),
    ]
