# Generated by Django 5.0.7 on 2024-08-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
