# Generated by Django 5.0.7 on 2024-08-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="customer",
            name="unique_email",
        ),
        migrations.RemoveConstraint(
            model_name="customer",
            name="unique_user_email",
        ),
        migrations.RemoveConstraint(
            model_name="customer",
            name="unique_user_first_last_name",
        ),
        migrations.RemoveIndex(
            model_name="customer",
            name="customer_email_c21aac_idx",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="date_of_join",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="last_name",
        ),
    ]
