# Generated by Django 5.0.7 on 2024-07-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["username"], name="Customer_cu_usernam_6d12d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["email"], name="Customer_cu_email_fbec5b_idx"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(fields=("email",), name="unique_email"),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("contact_number",), name="unique_contact_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("username", "email"), name="unique_username_email"
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                fields=("username", "first_name", "last_name"),
                name="unique_username_firstname_lastname",
            ),
        ),
    ]
