# Generated by Django 5.0.7 on 2024-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_servicerequest"),
        (
            "Mechanic",
            "0002_remove_mechanic_profile_pic_remove_mechanic_username_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="service_needed",
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="vehicle_no",
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name="servicerequest",
            constraint=models.UniqueConstraint(
                fields=(
                    "customer",
                    "vehicle_no",
                    "problem_description",
                    "service_name",
                ),
                name="unique_service_request",
            ),
        ),
    ]
